#!/bin/sh
echo "commit cancelled" # pri chybe zpracovani VSC automaticky vypise obsah prvniho echo, proto tento text i kdyz ve vypisu konzole bude mast
echo "#####################"
echo "###### COMMIT-MSG git hook"
echo "###### Check that name of commit is in correct form: 'text: text"
exec powershell.exe -NoProfile -ExecutionPolicy Bypass -file ".\.githooks\commit-msg.ps1" $1
echo "#####################"
exit