#!/bin/sh
echo "commit cancelled" # when error occurs, VSC automatically output first echo here, therefore this strange output
echo "#####################"
echo "###### COMMIT-MSG git hook"
echo "###### Checks that name of commit is in correct form: 'text: text"
#__TODO__ uncomment line beneath if you want specific commit message format
#exec powershell.exe -NoProfile -ExecutionPolicy Bypass -file ".\.githooks\commit-msg.ps1" $1
echo "#####################"
exit