#!/bin/sh
echo "commit cancelled" # when error occurs, VSC automatically output first echo here, therefore this strange output
echo "#####################"
echo "###### POST-MERGE git hook"
echo "###### Notify if pull automerges files, that are actually modified"
exec powershell.exe -NoProfile -ExecutionPolicy Bypass -file ".\.githooks\post-merge.ps1"
echo "#####################"
exit