#!/bin/sh
echo "commit cancelled" # when error occurs, VSC automatically output first echo here, therefore this strange output
echo "#####################"
echo "###### PRE-COMMIT git hook"
echo "###### Various checks"
exec powershell.exe -NoProfile -ExecutionPolicy Bypass -file ".\.githooks\pre-commit.ps1"
echo "#####################"
exit